name: flutter_project_smait
description: A simple project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^4.0.4
  flutter_bloc: ^8.0.0
  bloc: ^8.0.1
  equatable: ^2.0.3
  intl: ^0.17.0
  json_annotation: ^4.0.1
  meta: ^1.3.0
  uuid: ^3.0.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true